"""Zero-Knowledge Execution Core for the Ghostshroud privacy stack."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, Protocol


class EthicsOracle(Protocol):
    """Interface for Ghostkey-316 ethics checks."""

    def check_ethics(self, signal: Dict[str, Any]) -> bool:
        """Return True if the action is ethically permitted."""


class ConsentOracle(Protocol):
    """Interface for querying the Consent-Based Transparency Layer."""

    def is_action_allowed(self, consent_scope: str, payload_hash: str) -> bool:
        """Return True if consent covers the requested computation."""


@dataclass
class ProverConfig:
    backend: str
    circuit_path: Path
    trusted_setup_path: Optional[Path] = None
    security_level: str = "128"


@dataclass
class CircuitDefinition:
    name: str
    description: str
    consent_scope: str
    ethics_signal: Dict[str, Any]
    config: ProverConfig
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ProofBundle:
    circuit: CircuitDefinition
    proof: bytes
    public_inputs: Dict[str, Any]
    commitments: Dict[str, Any]
    signature: bytes


class CircuitRegistry:
    """Registry for zero-knowledge circuits with consent and ethics metadata."""

    def __init__(self) -> None:
        self._registry: Dict[str, CircuitDefinition] = {}

    def register(self, circuit: CircuitDefinition) -> None:
        if circuit.name in self._registry:
            raise ValueError(f"Circuit '{circuit.name}' already registered")
        self._registry[circuit.name] = circuit

    def get(self, name: str) -> CircuitDefinition:
        try:
            return self._registry[name]
        except KeyError as exc:
            raise KeyError(f"Unknown circuit '{name}'") from exc


class Prover:
    """Generates zero-knowledge proofs without revealing private inputs."""

    def __init__(
        self,
        registry: CircuitRegistry,
        consent_oracle: ConsentOracle,
        ethics_oracle: EthicsOracle,
        pq_crypto: "PostQuantumCryptoSuite",
    ) -> None:
        self._registry = registry
        self._consent = consent_oracle
        self._ethics = ethics_oracle
        self._pq = pq_crypto

    def prove(self, circuit_name: str, witness: Dict[str, Any]) -> ProofBundle:
        circuit = self._registry.get(circuit_name)
        payload_hash = self._pq.hash_witness(witness)
        if not self._consent.is_action_allowed(circuit.consent_scope, payload_hash):
            raise PermissionError("Consent requirements not satisfied for circuit execution")
        if not self._ethics.check_ethics(circuit.ethics_signal):
            raise PermissionError("Ethical override prevented circuit execution")

        public_inputs = self._extract_public_inputs(witness, circuit.metadata)
        proof_bytes = self._generate_proof_bytes(circuit, witness, public_inputs)
        commitments = self._pq.commit_payload(witness, circuit.metadata)
        signature = self._pq.sign_proof(proof_bytes, commitments)
        return ProofBundle(
            circuit=circuit,
            proof=proof_bytes,
            public_inputs=public_inputs,
            commitments=commitments,
            signature=signature,
        )

    def _generate_proof_bytes(
        self,
        circuit: CircuitDefinition,
        witness: Dict[str, Any],
        public_inputs: Dict[str, Any],
    ) -> bytes:
        # Placeholder for actual proving logic that would leverage SNARK/STARK tooling.
        transcript = (
            f"{circuit.name}:{public_inputs}:{circuit.config.backend}:{circuit.config.security_level}:"
            f"{self._pq.hash_witness(witness)}"
        )
        return transcript.encode("utf-8")

    def _extract_public_inputs(self, witness: Dict[str, Any], metadata: Dict[str, Any]) -> Dict[str, Any]:
        public_keys = metadata.get("public_inputs", [])
        return {key: witness[key] for key in public_keys if key in witness}


class Verifier:
    """Verifies zero-knowledge proofs generated by the Prover."""

    def __init__(self, pq_crypto: "PostQuantumCryptoSuite", ethics_oracle: EthicsOracle) -> None:
        self._pq = pq_crypto
        self._ethics = ethics_oracle

    def verify(self, bundle: ProofBundle) -> bool:
        if not self._ethics.check_ethics(bundle.circuit.ethics_signal):
            return False
        if not self._pq.verify_signature(bundle.proof, bundle.commitments, bundle.signature):
            return False
        return self._verify_proof(bundle)

    def _verify_proof(self, bundle: ProofBundle) -> bool:
        expected_prefix = (
            f"{bundle.circuit.name}:{bundle.public_inputs}:{bundle.circuit.config.backend}:"
            f"{bundle.circuit.config.security_level}:"
        )
        return bundle.proof.decode("utf-8").startswith(expected_prefix)


class PostQuantumCryptoSuite(Protocol):
    """Protocol describing the post-quantum primitives used across the stack."""

    def hash_witness(self, witness: Dict[str, Any]) -> str:
        ...

    def commit_payload(self, witness: Dict[str, Any], metadata: Dict[str, Any]) -> Dict[str, Any]:
        ...

    def sign_proof(self, proof: bytes, commitments: Dict[str, Any]) -> bytes:
        ...

    def verify_signature(self, proof: bytes, commitments: Dict[str, Any], signature: bytes) -> bool:
        ...


class DeterministicPQSuite:
    """Deterministic reference implementation useful for testing."""

    def __init__(self, secret_key: bytes, public_key: bytes) -> None:
        self._secret_key = secret_key
        self._public_key = public_key

    def hash_witness(self, witness: Dict[str, Any]) -> str:
        return str(hash(tuple(sorted(witness.items()))))

    def commit_payload(self, witness: Dict[str, Any], metadata: Dict[str, Any]) -> Dict[str, Any]:
        salt = metadata.get("commit_salt", "ghostshroud")
        commitment = f"{salt}:{witness}".encode("utf-8")
        return {"commitment": commitment.hex()}

    def sign_proof(self, proof: bytes, commitments: Dict[str, Any]) -> bytes:
        message = proof + commitments["commitment"].encode("utf-8")
        return message + self._secret_key

    def verify_signature(self, proof: bytes, commitments: Dict[str, Any], signature: bytes) -> bool:
        expected = proof + commitments["commitment"].encode("utf-8") + self._secret_key
        return signature == expected


__all__ = [
    "CircuitDefinition",
    "CircuitRegistry",
    "DeterministicPQSuite",
    "EthicsOracle",
    "PostQuantumCryptoSuite",
    "Prover",
    "ProverConfig",
    "ProofBundle",
    "Verifier",
]
